test_queries = [
    "python",
    "programming",
    "data structures",
    "machine learning",
    "web development",
    "algorithms",
    "python programming language",
    "test development",
    "indexing",
    "search engine",
    "html css javascript",
    "artificial intelligence",
    "software engineering",
    "computer science",
    "database",
    "networking",
    "security",
    "testing code quality",
    "development purposes",
    "various words phrases",
    "xyzabc123",
    "nonexistent term",
    "a",
    "the",
    "and or",
]

